name: CI

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          
      - name: Create initial log if not exists
        run: |
          if [ ! -f logs.txt ]; then
            echo "✨ Logs Started: $(date '+%Y-%m-%d %H:%M:%S %Z') ✨" > logs.txt
            git add logs.txt
            git config user.name "${{ secrets.USERNAME }}"
            git config user.email "${{ secrets.EMAIL }}"
            git commit -m "Hello World!"
            git push origin main
          fi
          
      - name: Update log with stylish date
        run: |
          echo "🕒 $(date '+%Y-%m-%d %H:%M:%S %Z') | System Check #$(wc -l < logs.txt) ✅" >> logs.txt
          git add logs.txt
          git config user.name "${{ secrets.USERNAME }}"
          git config user.email "${{ secrets.EMAIL }}"
          git commit -m "Hello World!"
          git push origin main || echo "Nothing to push."
          
      - name: Clean last line
        run: |
          sed -i '$ d' logs.txt
          git add logs.txt
          git config user.name "${{ secrets.USERNAME }}"
          git config user.email "${{ secrets.EMAIL }}"
          git commit -m "Hello World!"
          git push origin main || echo "Nothing to push."